[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "flask_ujson"
authors = [{name = "David Carmichael", email = "david@uilix.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com"
